### ISSUE TITLE
Ping-Skill Mycroft

### ISSUE THREAD

**Issue by riggs498** [nogre/mycroft-ping#1]
I have installed your ping skill on the Mycroft server. Here is the error I am getting

2017-07-23 13:30:58,074 - mycroft.skills.core - ERROR - An error occurred while processing a request in PingSkill
Traceback (most recent call last):
File "/home/riggs498/mycroft-core/mycroft/skills/core.py", line 242, in receive_handler
handler(message)
File "/opt/mycroft/skills/ping-skill/__init__.py", line 48, in handle_ping_intent
+ hosts[k][1][(hosts[k][1]).find("//")+2:])
File "/usr/lib/python2.7/commands.py", line 61, in getstatusoutput
sts = pipe.close()
IOError: [Errno 10] No child processes
2017-07-23 13:30:58,080 - Skills - DEBUG - {"type": "recognizer_loop:audio_output_start", "data": {}, "context": null}
2017-07-23 13:30:58,088 - Skills - DEBUG - {"type": "enclosure.eyes.blink", "data": {"side": "b"}, "context": null}
2017-07-23 13:30:58,080 - SpeechClient - INFO - Speak: An error occurred while processing a request in PingSkill

**Comment by nogre** [comment]
hmm. I hadn't tried to install it on a server, only a local setup. I'll take a look.

**Comment by jrwarwick** [comment]
@riggs498 you might want to retest. Quite a bit has changed since then. Make sure you are all up to date on packaging and Python versions and stuff first, though.
