### ISSUE TITLE
python3 compatibility: commands module deprecation

### ISSUE THREAD

**Issue by jrwarwick** [nogre/mycroft-ping#8]
19:28:24.405 - mycroft.skills.core:load_skill:166 - ERROR - Failed to load skill: ping-skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 128, in load_skill
    imp.PY_SOURCE))
  File "/opt/venvs/mycroft-core/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/opt/venvs/mycroft-core/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/opt/mycroft/skills/ping-skill/__init__.py", line 4, in <module>
    import commands
**ImportError: No module named 'commands'**

https://python-forum.io/Thread-import-commands-modules-not-working-in-python-3-6-0
Recommend refactoring with:  https://docs.python.org/3/library/subprocess.html

**Comment by jrwarwick** [comment]
After all this time, I'm still not clear on all the github etiquette for collaborative development. The pull request was accepted, and the merge succeeded. I think that makes issue wrapped up and ready for closure. I see here I have a "Close and comment" button. Would you like me to do that? Or would you like me to respect your ownership of the repository by letting you close the issue whenever you desire?

**Comment by nogre** [comment]
I'm no better at github etiquette. I haven't been doing much on github lately and must have just missed the notification when this pull was initially submitted. It all looks good to me.

**Comment by jrwarwick** [comment]
Aforementioned PR #9 has resolved the issue and ping skill has been running in a stable fashion on my mark 1 for a while now.
